---
- name: install minikube
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
- name: install kvm packages
  apt:
    name: "{{ item }}"
  loop:
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils

- name: add minikube group
  group:
    name: minikube
- name: add minikube user
  user:
    name: minikube
    group: minikube
    groups:
      - libvirt
      - kvm

